### ISSUE TITLE
The webpage ends in an error

### ISSUE THREAD

**Issue by AGSCL** [lbraglia/rioweb#1]
Hi, 

I replicated a small part of your webpage, but is not possible for me, because I can only download a text file. 
I explain it in more detail in this [forum](https://stackoverflow.com/questions/60873486/create-a-shiny-app-to-upload-a-stata-dataset-and-convert-it-into-a-spss-file)

Thanks you in advance

**Comment by lbraglia** [comment]
i'm sorry this tickets are for bug in rioweb, stackoverflow is the right place to ask for help
